name: "Less is more - artifact size"
description: "Be aware of the increase percentage of your artifact."
author: "Guilherme H. Caponetto"
branding:
  icon: "bar-chart-2"
  color: "purple"
inputs:
  released_artifact_name:
    description: "The file name of the released artifact (or part of it)."
    required: true
  artifact_path:
    description: "The path of the current artifact that has been built."
    required: true
  max_increase_percentage:
    description: "The maximum increase percentage allowed."
    required: true
  github_token:
    description: "The token to authenticate Octokit (default: do not use token)."
    required: false
  fail_execution:
    description: "Fail the execution if the artifact is bigger than allowed (default: true)."
    required: false
runs:
  using: "node12"
  main: "dist/index.js"
