name: "CI"

on:
  push:
    branches: [main]
  pull_request:
    branches: "**"

concurrency:
  group: ${{ github.event.pull_request && format('ci-pr-{0}', github.event.pull_request.number) || 'ci-push-main' }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: "Checkout"
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: "Setup Node"
      uses: actions/setup-node@v1
      with:
        node-version: 16.2.0

    - name: "Install dependencies"
      run: npm install

    - name: "Check format"
      run: npm run format-check

    - name: "Lint"
      run: npm run lint

    - name: "Build"
      run: npm run build

    - name: "Test"
      run: npm test

    - name: "Upload coverage report"
      uses: actions/upload-artifact@v2
      with:
        name: coverage
        path: coverage/
